application: edge-chat-example
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /css
  static_dir: css

- url: /js
  static_dir: js

- url: .*
  script: chat.app
  login: required

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: "2.6"
